runtime: nodejs10
entrypoint: node ./server/server.js

env_variables:
  CLOUD_INSTANCE: pawz-down:us-central1:pawz-down-db

instance_class: F2

resources:
  # cpu: 0.5
  memory_gb: 0.25
  # disk_size_gb: 10